"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
__export(require("./service"));
__export(require("./injectable"));
__export(require("./store"));
__export(require("./action-decorator"));
__export(require("./pluck-out"));
__export(require("./change-detection-strategy"));
__export(require("./component-decorators"));
__export(require("./convert-unix-timestamp-to-date"));
__export(require("./service-decorator"));
__export(require("./add-or-update"));
__export(require("./action-creator"));
__export(require("./view-encapsulation"));
__export(require("./fetch"));
__export(require("./provide"));
__export(require("./provide-action"));
__export(require("./get-x"));
__export(require("./is-between"));
__export(require("./translate-x"));
__export(require("./translate-x-y"));
exports.Observable = Rx.Observable;
require("./local-storage-manager-provider");
require("./store");
require("./add-or-update");
require("./append-to-body-async");
require("./auth-interceptor");
require("./convert-unix-timestamp-to-date");
require("./debounce");
require("./extend-css-async");
require("./get-from-url-sync");
require("./fetch");
require("./get-x");
require("./invoke-async");
require("./component-extension");
require("./position.service");
require("./remove-element");
require("./rectangle.service");
require("./ruler.service");
require("./safe-digest");
require("./set-opacity-async");
require("./space.service");
require("./translate-x");
require("./translate-x-y");
require("./translate-x-async");
require("./template.service");
var coreApp = angular.module("app.core", [
    "ngSanitize",
    "authInterceptor",
    "localStorageManager",
    "store",
    "addOrUpdate",
    "appendToBodyAsync",
    "convertUnixTimestampToDate",
    "debounce",
    "extendCssAsync",
    "getFromUrlSync",
    "getX",
    "invokeAsync",
    "fetch",
    "position",
    "removeElement",
    "rectangle",
    "ruler",
    "safeDigest",
    "setOpacityAsync",
    "space",
    "rectangle",
    "translateX",
    "translateXY",
    "translateXAsync",
    "template"
]);
//# sourceMappingURL=index.js.map